# apiVersion: v1
# kind: Secret
# metadata:
#   name: influxdb-license
# stringData:
#   json: YOUR JSON KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-shared-secret
stringData:
  secret: MY RANDOM STRING
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: influxdb-tls
# type: kubernetes.io/tls
# stringData:
#   tls.crt: |
#     SOME CERTIFICATE
#   tls.key: |
#     SOME KEY
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: influxdb-ddl-dml
# data:
#   ddl: |
#     CREATE DATABASE original
#     CREATE RETENTION POLICY oneday ON original DURATION 1d REPLICATION 1
#   dml: ""
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: test-role
  apiGroup: rbac.authorization.k8s.io
---
